apply all recommended changes by shellcheck

diff --git a/bin/snap-sync b/bin/snap-sync
--- a/bin/snap-sync
+++ b/bin/snap-sync
@@ -14,28 +14,28 @@ name="snap-sync"
 
 TMPDIR=$(mktemp -d)
 PIPE=$TMPDIR/$name.out
-mkfifo $PIPE
-systemd-cat -t "$name" < $PIPE &
-exec 3>$PIPE
+mkfifo "$PIPE"
+systemd-cat -t "$name" < "$PIPE" &
+exec 3>"$PIPE"
 
 notify_error() {
     for u in $(users); do
-        sudo -u $u DISPLAY=:0 \
-        DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$(sudo -u $u id -u)/bus \
+        sudo -u "$u" DISPLAY=:0 \
+        DBUS_SESSION_BUS_ADDRESS=unix:path="/run/user/$(sudo -u "$u" id -u)/bus" \
         notify-send -a $name "$1" "$2" --icon=dialog-error
     done
 }
 
-out() { 
-    printf "$1 $2\n" "${@:3}" | tee $PIPE
+out() {
+    printf "%s %s\n%s" "$1" "$2" "${@:3}" | tee "$PIPE"
 }
 
-error() { 
+error() {
     out "==> ERROR:" "$@"
     notify_error 'Error' 'Check journal for more information.'
 } >&2
 
-die() { 
+die() {
     error "$@"
     exit 1
 }
@@ -49,11 +49,11 @@ traperror() {
     exit 1
 }
 
-trapkill() { 
-    die "Exited due to user intervention." 
+trapkill() {
+    die "Exited due to user intervention."
 }
 
-[[ $EUID -ne 0 ]] && die "Script must be run as root." 
+[[ $EUID -ne 0 ]] && die "Script must be run as root."
 
 trap 'traperror ${LINENO} $? "$BASH_COMMAND" $BASH_LINENO "${FUNCNAME[@]}"' ERR
 trap trapkill SIGTERM SIGINT
@@ -80,8 +80,8 @@ Options:
                           directory name on first backup"
  -u, --UUID <UUID>        Specify the UUID of the mounted BTRFS subvolume to back up to. Otherwise will prompt."
                           If multiple mount points are found with the same UUID, will prompt user."
- --remote <address>       Send the snapshot backup to a remote machine. The snapshot will be sent via ssh. You 
-                          should specify the remote machine's hostname or ip address. The 'root' user must be 
+ --remote <address>       Send the snapshot backup to a remote machine. The snapshot will be sent via ssh. You
+                          should specify the remote machine's hostname or ip address. The 'root' user must be
                           permitted to login on the remote machine.
 
 EOF
@@ -154,7 +154,7 @@ for x in $UUIDS; do
     UUIDS_ARRAY[$i]=$x
     if [[ "$x" == "$uuid_cmdline" ]]; then
         disk=$i
-        disk_count=$(($disk_count+1))
+        disk_count=$(( disk_count + 1 ))
     fi
     i=$((i+1))
 done
@@ -165,8 +165,8 @@ for x in $TARGETS; do
     i=$((i+1))
 done
 
-if [[ "$disk_count" > 1 ]]; then
-    printf "Multiple mount points were found with UUID $uuid_cmdline.\n"
+if [[ "$disk_count" -gt 1 ]]; then
+    printf "Multiple mount points were found with UUID %s.\n" "$uuid_cmdline"
     disk="-1"
 fi
 
@@ -177,7 +177,7 @@ if [[ "$disk" == -1 ]]; then
     if [[ -z $ssh ]]; then
         printf "Select a mounted BTRFS device on your local machine to backup to.\n"
     else
-        printf "Select a mounted BTRFS device on $remote to backup to.\n"
+        printf "Select a mounted BTRFS device on %s to backup to.\n" "$remote"
     fi
     while [[ $disk -lt 0 || $disk -gt $i ]]; do
         for x in "${!TARGETS_ARRAY[@]}"; do
@@ -193,20 +193,21 @@ if [[ "$disk" == -1 ]]; then
     if [[ $disk == 0 ]]; then
         exit 0
     fi
-    disk=$(($disk-1))
+    disk=$(( disk - 1 ))
 fi
 
 selected_uuid="${UUIDS_ARRAY[$((disk))]}"
 selected_mnt="${TARGETS_ARRAY[$((disk))]}"
-printf "\nYou selected the disk with UUID %s.\n" "$selected_uuid" | tee $PIPE
+printf "\nYou selected the disk with UUID %s.\n" "$selected_uuid" | tee "$PIPE"
 if [[ -z $ssh ]]; then
-    printf "The disk is mounted at %s.\n" "$selected_mnt" | tee $PIPE
+    printf "The disk is mounted at %s.\n" "$selected_mnt" | tee "$PIPE"
 else
-    printf "The disk is mounted at %s:%s.\n" "$remote" "$selected_mnt" | tee $PIPE
+    printf "The disk is mounted at %s:%s.\n" "$remote" "$selected_mnt" | tee "$PIPE"
 fi
 
 if [[ -f /etc/conf.d/snapper ]]; then
-    source /etc/conf.d/snapper 
+    # shellcheck disable=SC1091
+    source /etc/conf.d/snapper
 else
     die "/etc/conf.d/snapper does not exist!"
 fi
@@ -223,25 +224,26 @@ declare -a NEW_INFO_ARRAY
 declare -a BACKUPLOC_ARRAY
 declare -a CONT_BACKUP_ARRAY
 
-printf "\nInitial configuration...\n" | tee $PIPE
+printf "\nInitial configuration...\n" | tee "$PIPE"
 
 # Initial configuration of where backup directories are
 i=0
 for x in $selected_configs; do
 
-    if [[ "$(snapper -c $x list -t single | awk '/'$name' backup in progress/ {cnt++} END {print cnt}')" -gt 0 ]]; then
-        printf "\nNOTE: Previous failed $name backup snapshots found for '$x'.\n" | tee $PIPE
+    if [[ "$(snapper -c "$x" list -t single | awk '/'$name' backup in progress/ {cnt++} END {print cnt}')" -gt 0 ]]; then
+        printf "\nNOTE: Previous failed %s backup snapshots found for '%s'.\n" "$name" "$x" | tee "$PIPE"
     fi
 
     SNAP_SYNC_EXCLUDE=no
 
     if [[ -f "/etc/snapper/configs/$x" ]]; then
-        source /etc/snapper/configs/$x
+        # shellcheck disable=SC1090
+        source "/etc/snapper/configs/$x"
     else
         die "Selected snapper configuration $x does not exist."
     fi
 
-    if [[ $SNAP_SYNC_EXCLUDE == "yes" ]]; then 
+    if [[ $SNAP_SYNC_EXCLUDE == "yes" ]]; then
         continue
     fi
 
@@ -262,21 +264,21 @@ for x in $selected_configs; do
     else
         mybackupdir=$(snapper -c "$x" list -t single | awk -F"|" '/'"$selected_uuid"'/ {print $5}' | awk -F "," '/backupdir/ {print $1}' | awk -F"=" '{print $2}')
         BACKUPDIR="$selected_mnt/$mybackupdir"
-        $ssh test -d $BACKUPDIR || die "%s is not a directory on %s.\n" "$BACKUPDIR" "$selected_uuid"
+        $ssh test -d "$BACKUPDIR" || die "%s is not a directory on %s.\n" "$BACKUPDIR" "$selected_uuid"
     fi
     BACKUPDIRS_ARRAY[$i]="$BACKUPDIR"
     MYBACKUPDIR_ARRAY[$i]="$mybackupdir"
 
-    printf "Creating new snapshot for $x...\n" | tee $PIPE
+    printf "Creating new snapshot for %s...\n" "$x" | tee "$PIPE"
     new_num=$(snapper -c "$x" create --print-number -d "$name backup in progress")
     new_snap=$SUBVOLUME/.snapshots/$new_num/snapshot
     new_info=$SUBVOLUME/.snapshots/$new_num/info.xml
     sync
     backup_location=$BACKUPDIR/$x/$new_num/
-    if [[ -z $ssh ]]; then
-        printf "Will backup %s to %s\n" "$new_snap" "$backup_location/snapshot" | tee $PIPE
+    if [[ -z "$ssh" ]]; then
+        printf "Will backup %s to %s\n" "$new_snap" "$backup_location/snapshot" | tee "$PIPE"
     else
-        printf "Will backup %s to %s\n" "$new_snap" "$remote":"$backup_location/snapshot" | tee $PIPE
+        printf "Will backup %s to %s\n" "$new_snap" "$remote:$backup_location/snapshot" | tee "$PIPE"
     fi
 
     NEW_NUM_ARRAY[$i]="$new_num"
@@ -304,30 +306,31 @@ for x in $selected_configs; do
     if [[ "$cont_backup" != [Yy]"es" && "$cont_backup" != [Yy] && -n "$cont_backup" ]]; then
         CONT_BACKUP_ARRAY[$i]="no"
         printf "Aborting backup for this configuration.\n"
-        snapper -c $x delete $new_num
+        snapper -c "$x" delete "$new_num"
     fi
 
-    i=$(($i+1))
+    i=$(( i + 1 ))
 
 done
 
 # Actual backing up
-printf "\nPerforming backups...\n" | tee $PIPE
+printf "\nPerforming backups...\n" | tee "$PIPE"
 i=-1
 for x in $selected_configs; do
 
-    i=$(($i+1))
+    i=$(( i + 1 ))
 
     SNAP_SYNC_EXCLUDE=no
 
     if [[ -f "/etc/snapper/configs/$x" ]]; then
-        source /etc/snapper/configs/$x
+        # shellcheck disable=SC1090
+        source "/etc/snapper/configs/$x"
     else
         die "Selected snapper configuration $x does not exist."
     fi
 
     cont_backup=${CONT_BACKUP_ARRAY[$i]}
-    if [[ $cont_backup == "no" || $SNAP_SYNC_EXCLUDE == "yes" ]]; then 
+    if [[ $cont_backup == "no" || $SNAP_SYNC_EXCLUDE == "yes" ]]; then
         notify_info "Backup in progress" "NOTE: Skipping $x configuration."
         continue
     fi
@@ -345,21 +348,21 @@ for x in $selected_configs; do
     new_info="${NEW_INFO_ARRAY[$i]}"
     backup_location="${BACKUPLOC_ARRAY[$i]}"
 
-    $ssh mkdir -p $backup_location
+    $ssh mkdir -p "$backup_location"
 
     if [[ -z "$old_num" ]]; then
-        printf "Sending first snapshot for %s...\n" "$x" | tee $PIPE  
+        printf "Sending first snapshot for %s...\n" "$x" | tee "$PIPE"
         btrfs send "$new_snap" | $ssh btrfs receive "$backup_location" &>/dev/null
 
     else
 
-        printf "Sending incremental snapshot for %s...\n" "$x" | tee $PIPE  
+        printf "Sending incremental snapshot for %s...\n" "$x" | tee "$PIPE"
         # Sends the difference between the new snapshot and old snapshot to the
         # backup location. Using the -c flag instead of -p tells it that there
         # is an identical subvolume to the old snapshot at the receiving
         # location where it can get its data. This helps speed up the transfer.
         btrfs send -c "$old_snap" "$new_snap" | $ssh btrfs receive "$backup_location"
-        printf "Deleting old snapshot for $x...\n" | tee $PIPE
+        printf "Deleting old snapshot for %s...\n" "$x" | tee "$PIPE"
         snapper -c "$x" delete "$old_num"
     fi
 
@@ -375,14 +378,14 @@ for x in $selected_configs; do
     userdata="backupdir=$mybackupdir, uuid=$selected_uuid"
 
     # Tag new snapshot as the latest
-    printf "Tagging new snapshot as latest backup for $x...\n" | tee $PIPE
+    printf "Tagging new snapshot as latest backup for %s...\n" "$x" | tee "$PIPE"
     snapper -v -c "$x" modify -d "$description" -u "$userdata" "$new_num"
 
-    printf "Backup complete for configuration %s.\n" "$x" > $PIPE
+    printf "Backup complete for configuration %s.\n" "$x" > "$PIPE"
 
 done
 
-printf "\nDone!\n" | tee $PIPE
+printf "\nDone!\n" | tee "$PIPE"
 exec 3>&-
 
 if [[ "$uuid_cmdline" != "none" ]]; then
